package cn.codertq.springrobot.domain.entity;

public class CfUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_user.id
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_user.qq_number
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    private Long qqNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_user.cf_nickname
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    private String cfNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_user.cf_rating
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    private Integer cfRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_user.hidden
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    private Integer hidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_user.candidate
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    private Integer candidate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_user.id
     *
     * @return the value of cf_user.id
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_user.id
     *
     * @param id the value for cf_user.id
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_user.qq_number
     *
     * @return the value of cf_user.qq_number
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public Long getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_user.qq_number
     *
     * @param qqNumber the value for cf_user.qq_number
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public void setQqNumber(Long qqNumber) {
        this.qqNumber = qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_user.cf_nickname
     *
     * @return the value of cf_user.cf_nickname
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public String getCfNickname() {
        return cfNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_user.cf_nickname
     *
     * @param cfNickname the value for cf_user.cf_nickname
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public void setCfNickname(String cfNickname) {
        this.cfNickname = cfNickname == null ? null : cfNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_user.cf_rating
     *
     * @return the value of cf_user.cf_rating
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public Integer getCfRating() {
        return cfRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_user.cf_rating
     *
     * @param cfRating the value for cf_user.cf_rating
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public void setCfRating(Integer cfRating) {
        this.cfRating = cfRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_user.hidden
     *
     * @return the value of cf_user.hidden
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_user.hidden
     *
     * @param hidden the value for cf_user.hidden
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_user.candidate
     *
     * @return the value of cf_user.candidate
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public Integer getCandidate() {
        return candidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_user.candidate
     *
     * @param candidate the value for cf_user.candidate
     *
     * @mbg.generated Mon Jan 24 10:50:12 CST 2022
     */
    public void setCandidate(Integer candidate) {
        this.candidate = candidate;
    }
}